# https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/

["vimfiles/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

